from ...graphics.images_loader import CUBE_PORTAL

VEL = 8
WIN_WIDTH = 800
WIN_HEIGHT = 680
CUBE_GRAV = 0.8
CUBE_ROTATION_VEL = 3
INITIAL_X = 150
PORTAL_HEIGHT = CUBE_PORTAL.get_height()
ORB_ROTATION_VEL = 6
ORB_GRAV = 0.6
DRAG_ROTATION_VEL = 3
DRAG_GRAV = 0.2
DRAG_MAX_VEL = 6
CYCL_GRAV = 30
